name: Run Postman Tests

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Newman and htmlextra
        run: npm install -g newman newman-reporter-htmlextra
      - name: Create reports directory
        run: mkdir -p reports
      - name: Run Postman Tests
        run: newman run RS_Commerce_Regression.postman_collection.json -r htmlextra --reporter-htmlextra-export reports/report.html
